[package]
name = "fourth_lesson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name ="iterator"
path ="src/iterator.rs"


[[bin]]
name ="closure"
path ="src/closure.rs"